// Generated by CoffeeScript 1.6.3
(function() {
  var element, _i, _len, _ref;

  _ref = $('.unit-div');
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    element = _ref[_i];
    $(element).data('expanded', false);
  }

  $('.unit-div').on('click', function(e) {
    var _j, _len1, _ref1, _results;
    if ($(this).data("expanded") === false) {
      $(this).css({
        'height': "24em",
        'overflow-y': 'auto',
        'overflow-x': 'auto',
        'overflow': 'auto'
      });
      $(this).data("expanded", true);
    } else if ($(this).data("expanded") === true) {
      $(this).css({
        'height': '',
        'overflow': '',
        'overflow-x': '',
        'overflow-y': ''
      });
      $(this).scrollTop(0);
      $(this).data("expanded", false);
    }
    _ref1 = $('.unit-div');
    _results = [];
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      element = _ref1[_j];
      if ($(element)[0] !== $(this)[0] && $(element).data("expanded") === true) {
        $(element).css({
          'height': '',
          'overflow': '',
          'overflow-y': '',
          'overflow-x': ''
        });
        $(element).scrollTop(0);
        _results.push($(element).data("expanded", false));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });

}).call(this);
