// Generated by CoffeeScript 1.6.3
(function() {
  $('.segment').on('click', function(e) {
    var boxID, element, _i, _len, _ref;
    boxID = "#" + $(this).attr("id") + "-box";
    _ref = $('.unit-section');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      element = _ref[_i];
      if ($(element)[0] !== $(boxID)[0] && $(element).hasClass("disabled") === false) {
        $(element).toggleClass("disabled");
      }
    }
    if ($(boxID).hasClass("disabled")) {
      return $(boxID).toggleClass("disabled");
    }
  });

}).call(this);
